export const PROJECT_ID =
  process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID ??
  "YOUR WALLET CONNECT PROJECT ID";

export const XELLAR_APP_ID =
  process.env.NEXT_PUBLIC_XELLAR_APP_ID ?? "YOUR XELLAR APP ID ID";
